-- Lead Input Tallies Migration
-- Creates table for tracking daily tallies per user, sub-input, and outcome
-- Idempotent migration - safe to run multiple times

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema='public' AND table_name='lead_input_tallies'
  ) THEN
    CREATE TABLE public.lead_input_tallies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id UUID NOT NULL,
      input_date DATE NOT NULL DEFAULT (CURRENT_DATE),
      sub_input TEXT NOT NULL,
      outcome TEXT NOT NULL,
      count INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  END IF;

  -- Add columns if table existed without them
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema='public' AND table_name='lead_input_tallies' AND column_name='count'
  ) THEN
    ALTER TABLE public.lead_input_tallies ADD COLUMN count INTEGER NOT NULL DEFAULT 0;
  END IF;

  -- Unique index to prevent duplicates per user/day/sub_input/outcome
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='ux_tallies_user_day_sub_outcome'
  ) THEN
    CREATE UNIQUE INDEX ux_tallies_user_day_sub_outcome
      ON public.lead_input_tallies (user_id, input_date, sub_input, outcome);
  END IF;

  -- Check constraints for allowed values (drop/recreate for idempotency)
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_schema='public' AND table_name='lead_input_tallies' AND constraint_name='lead_input_tallies_sub_input_check'
  ) THEN
    ALTER TABLE public.lead_input_tallies DROP CONSTRAINT lead_input_tallies_sub_input_check;
  END IF;
  IF EXISTS (
    SELECT 1 FROM information_schema.table_constraints
    WHERE table_schema='public' AND table_name='lead_input_tallies' AND constraint_name='lead_input_tallies_outcome_check'
  ) THEN
    ALTER TABLE public.lead_input_tallies DROP CONSTRAINT lead_input_tallies_outcome_check;
  END IF;

  ALTER TABLE public.lead_input_tallies
    ADD CONSTRAINT lead_input_tallies_sub_input_check CHECK (
      sub_input IN ('door_knocks','tags_put','calls_made','referrals','inbound')
    );

  ALTER TABLE public.lead_input_tallies
    ADD CONSTRAINT lead_input_tallies_outcome_check CHECK (
      outcome IN ('interested','not_interested','not_home','unqualified','already_has_product','appointment_set')
    );
END $$;

-- Keep 'count' non-negative
CREATE OR REPLACE FUNCTION public.enforce_nonnegative_count()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.count < 0 THEN NEW.count := 0; END IF;
  NEW.updated_at := NOW();
  RETURN NEW;
END $$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname='trg_nonneg_count_tallies'
  ) THEN
    CREATE TRIGGER trg_nonneg_count_tallies
    BEFORE INSERT OR UPDATE ON public.lead_input_tallies
    FOR EACH ROW EXECUTE FUNCTION public.enforce_nonnegative_count();
  END IF;
END $$;

-- Optional: fast lookups
CREATE INDEX IF NOT EXISTS idx_tallies_user_date ON public.lead_input_tallies (user_id, input_date);
CREATE INDEX IF NOT EXISTS idx_tallies_sub_input ON public.lead_input_tallies (sub_input);
CREATE INDEX IF NOT EXISTS idx_tallies_outcome ON public.lead_input_tallies (outcome);

-- RPC for atomic increment
CREATE OR REPLACE FUNCTION public.increment_tally_rpc(
  p_user_id UUID, p_date DATE, p_sub TEXT, p_out TEXT
) RETURNS VOID LANGUAGE sql AS $$
  INSERT INTO public.lead_input_tallies (user_id, input_date, sub_input, outcome, count)
  VALUES (p_user_id, p_date, p_sub, p_out, 1)
  ON CONFLICT (user_id, input_date, sub_input, outcome)
  DO UPDATE SET count = public.lead_input_tallies.count + 1, updated_at = NOW();
$$;

-- RPC for atomic decrement
CREATE OR REPLACE FUNCTION public.decrement_tally_rpc(
  p_user_id UUID, p_date DATE, p_sub TEXT, p_out TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.lead_input_tallies
  SET count = GREATEST(count - 1, 0), updated_at = NOW()
  WHERE user_id = p_user_id AND input_date = p_date AND sub_input = p_sub AND outcome = p_out;
  -- optional: do nothing if row doesn't exist (no error)
END $$;

-- RPC for resetting all outcomes for a sub-input on a given date
CREATE OR REPLACE FUNCTION public.reset_tallies_for_sub_input(
  p_user_id UUID, p_date DATE, p_sub TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.lead_input_tallies
  SET count = 0, updated_at = NOW()
  WHERE user_id = p_user_id AND input_date = p_date AND sub_input = p_sub;
END $$;

-- Auth / RLS (adjust to project RLS pattern)
-- Ensure rows are only visible/editable by their owner.
-- If RLS is on:
-- ALTER TABLE public.lead_input_tallies ENABLE ROW LEVEL SECURITY;
-- CREATE POLICY "own-rows" ON public.lead_input_tallies
--   USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);
