-- SAFE DATABASE FIX FOR 1099SUITE
-- This script safely fixes all database issues without breaking existing data

-- ========================================
-- 1. FIX USER_SETTINGS TABLE (CURRENT ERROR)
-- ========================================

-- Drop and recreate user_settings table with correct structure
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema='public' AND table_name='user_settings'
  ) THEN
    DROP TABLE public.user_settings CASCADE;
  END IF;
END $$;

CREATE TABLE public.user_settings (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID REFERENCES public.users(id) ON DELETE CASCADE NOT NULL,
  settings_key TEXT NOT NULL,
  settings_value JSONB NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  UNIQUE(user_id, settings_key)
);

-- ========================================
-- 2. ENSURE LEAD_INPUT_TALLIES TABLE EXISTS
-- ========================================

-- Create lead_input_tallies table if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema='public' AND table_name='lead_input_tallies'
  ) THEN
    CREATE TABLE public.lead_input_tallies (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id UUID NOT NULL,
      input_date DATE NOT NULL DEFAULT (CURRENT_DATE),
      sub_input TEXT NOT NULL,
      outcome TEXT NOT NULL,
      count INTEGER NOT NULL DEFAULT 0,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    );
  END IF;
END $$;

-- ========================================
-- 3. ADD MISSING COLUMNS TO EXISTING TABLES
-- ========================================

-- Add missing columns to daily_inputs table
DO $$
BEGIN
  -- Add tally_counts column if it doesn't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema='public' AND table_name='daily_inputs' AND column_name='tally_counts'
  ) THEN
    ALTER TABLE public.daily_inputs ADD COLUMN tally_counts JSONB DEFAULT '{}';
  END IF;
  
  -- Add sub-input columns if they don't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema='public' AND table_name='daily_inputs' AND column_name='outreach_door_knocks'
  ) THEN
    ALTER TABLE public.daily_inputs ADD COLUMN outreach_door_knocks INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN outreach_tags_put INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN outreach_calls_made INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN outreach_referrals INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN outreach_inbound INTEGER DEFAULT 0;
  END IF;
  
  -- Add appointments sub-input columns if they don't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema='public' AND table_name='daily_inputs' AND column_name='appointments_set_door_knocks'
  ) THEN
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_set_door_knocks INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_set_tags_put INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_set_calls_made INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_set_referrals INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_set_inbound INTEGER DEFAULT 0;
  END IF;
  
  -- Add appointments held sub-input columns if they don't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema='public' AND table_name='daily_inputs' AND column_name='appointments_held_door_knocks'
  ) THEN
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_held_door_knocks INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_held_tags_put INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_held_calls_made INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_held_referrals INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN appointments_held_inbound INTEGER DEFAULT 0;
  END IF;
  
  -- Add deals closed sub-input columns if they don't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema='public' AND table_name='daily_inputs' AND column_name='deals_closed_door_knocks'
  ) THEN
    ALTER TABLE public.daily_inputs ADD COLUMN deals_closed_door_knocks INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN deals_closed_tags_put INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN deals_closed_calls_made INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN deals_closed_referrals INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN deals_closed_inbound INTEGER DEFAULT 0;
  END IF;
  
  -- Add accounts serviced sub-input columns if they don't exist
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema='public' AND table_name='daily_inputs' AND column_name='accounts_serviced_door_knocks'
  ) THEN
    ALTER TABLE public.daily_inputs ADD COLUMN accounts_serviced_door_knocks INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN accounts_serviced_tags_put INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN accounts_serviced_calls_made INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN accounts_serviced_referrals INTEGER DEFAULT 0;
    ALTER TABLE public.daily_inputs ADD COLUMN accounts_serviced_inbound INTEGER DEFAULT 0;
  END IF;
END $$;

-- ========================================
-- 4. ADD MISSING INDEXES AND CONSTRAINTS
-- ========================================

-- Add unique constraint to daily_inputs if it doesn't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM information_schema.table_constraints 
    WHERE table_schema='public' AND table_name='daily_inputs' AND constraint_name='daily_inputs_user_id_date_key'
  ) THEN
    ALTER TABLE public.daily_inputs ADD CONSTRAINT daily_inputs_user_id_date_key UNIQUE (user_id, date);
  END IF;
END $$;

-- Add indexes for user_settings
CREATE INDEX IF NOT EXISTS idx_user_settings_user_id ON public.user_settings (user_id);
CREATE INDEX IF NOT EXISTS idx_user_settings_key ON public.user_settings (settings_key);

-- Add indexes for lead_input_tallies
CREATE INDEX IF NOT EXISTS idx_tallies_user_date ON public.lead_input_tallies (user_id, input_date);
CREATE INDEX IF NOT EXISTS idx_tallies_sub_input ON public.lead_input_tallies (sub_input);
CREATE INDEX IF NOT EXISTS idx_tallies_outcome ON public.lead_input_tallies (outcome);

-- Add unique index for lead_input_tallies
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes WHERE schemaname='public' AND indexname='ux_tallies_user_day_sub_outcome'
  ) THEN
    CREATE UNIQUE INDEX ux_tallies_user_day_sub_outcome
      ON public.lead_input_tallies (user_id, input_date, sub_input, outcome);
  END IF;
END $$;

-- ========================================
-- 5. ADD MISSING FUNCTIONS AND TRIGGERS
-- ========================================

-- Create update_updated_at_column function if it doesn't exist
CREATE OR REPLACE FUNCTION public.update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ language 'plpgsql';

-- Create enforce_nonnegative_count function for tallies
CREATE OR REPLACE FUNCTION public.enforce_nonnegative_count()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  IF NEW.count < 0 THEN NEW.count := 0; END IF;
  NEW.updated_at := NOW();
  RETURN NEW;
END $$;

-- Add triggers if they don't exist
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname='update_user_settings_updated_at'
  ) THEN
    CREATE TRIGGER update_user_settings_updated_at 
      BEFORE UPDATE ON public.user_settings 
      FOR EACH ROW EXECUTE FUNCTION public.update_updated_at_column();
  END IF;
  
  IF NOT EXISTS (
    SELECT 1 FROM pg_trigger WHERE tgname='trg_nonneg_count_tallies'
  ) THEN
    CREATE TRIGGER trg_nonneg_count_tallies
      BEFORE INSERT OR UPDATE ON public.lead_input_tallies
      FOR EACH ROW EXECUTE FUNCTION public.enforce_nonnegative_count();
  END IF;
END $$;

-- ========================================
-- 6. ADD MISSING RPC FUNCTIONS
-- ========================================

-- RPC for atomic increment
CREATE OR REPLACE FUNCTION public.increment_tally_rpc(
  p_user_id UUID, p_date DATE, p_sub TEXT, p_out TEXT
) RETURNS VOID LANGUAGE sql AS $$
  INSERT INTO public.lead_input_tallies (user_id, input_date, sub_input, outcome, count)
  VALUES (p_user_id, p_date, p_sub, p_out, 1)
  ON CONFLICT (user_id, input_date, sub_input, outcome)
  DO UPDATE SET count = public.lead_input_tallies.count + 1, updated_at = NOW();
$$;

-- RPC for atomic decrement
CREATE OR REPLACE FUNCTION public.decrement_tally_rpc(
  p_user_id UUID, p_date DATE, p_sub TEXT, p_out TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.lead_input_tallies
  SET count = GREATEST(count - 1, 0), updated_at = NOW()
  WHERE user_id = p_user_id AND input_date = p_date AND sub_input = p_sub AND outcome = p_out;
END $$;

-- RPC for resetting all outcomes for a sub-input on a given date
CREATE OR REPLACE FUNCTION public.reset_tallies_for_sub_input(
  p_user_id UUID, p_date DATE, p_sub TEXT
) RETURNS VOID LANGUAGE plpgsql AS $$
BEGIN
  UPDATE public.lead_input_tallies
  SET count = 0, updated_at = NOW()
  WHERE user_id = p_user_id AND input_date = p_date AND sub_input = p_sub;
END $$;

-- ========================================
-- 7. ENABLE RLS AND ADD POLICIES
-- ========================================

-- Enable RLS on all tables
ALTER TABLE public.user_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.lead_input_tallies ENABLE ROW LEVEL SECURITY;

-- Add policies for user_settings (drop existing ones first)
DO $$
BEGIN
  -- Drop existing policies
  DROP POLICY IF EXISTS "Users can view own settings" ON public.user_settings;
  DROP POLICY IF EXISTS "Users can insert own settings" ON public.user_settings;
  DROP POLICY IF EXISTS "Users can update own settings" ON public.user_settings;
  DROP POLICY IF EXISTS "Users can delete own settings" ON public.user_settings;
END $$;

-- Create new policies
CREATE POLICY "Users can view own settings" ON public.user_settings
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own settings" ON public.user_settings
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own settings" ON public.user_settings
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own settings" ON public.user_settings
  FOR DELETE USING (auth.uid() = user_id);

-- Add policies for lead_input_tallies (drop existing ones first)
DO $$
BEGIN
  DROP POLICY IF EXISTS "Users can view own tallies" ON public.lead_input_tallies;
  DROP POLICY IF EXISTS "Users can insert own tallies" ON public.lead_input_tallies;
  DROP POLICY IF EXISTS "Users can update own tallies" ON public.lead_input_tallies;
  DROP POLICY IF EXISTS "Users can delete own tallies" ON public.lead_input_tallies;
END $$;

-- Create new policies
CREATE POLICY "Users can view own tallies" ON public.lead_input_tallies
  FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own tallies" ON public.lead_input_tallies
  FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own tallies" ON public.lead_input_tallies
  FOR UPDATE USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own tallies" ON public.lead_input_tallies
  FOR DELETE USING (auth.uid() = user_id);

-- ========================================
-- 8. VERIFICATION
-- ========================================

-- Check if all required tables exist
SELECT 
  'user_settings' as table_name,
  CASE WHEN EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema='public' AND table_name='user_settings'
  ) THEN 'EXISTS' ELSE 'MISSING' END as status
UNION ALL
SELECT 
  'lead_input_tallies' as table_name,
  CASE WHEN EXISTS (
    SELECT 1 FROM information_schema.tables 
    WHERE table_schema='public' AND table_name='lead_input_tallies'
  ) THEN 'EXISTS' ELSE 'MISSING' END as status;

-- Check if settings_key column exists
SELECT 
  'settings_key column' as check_name,
  CASE WHEN EXISTS (
    SELECT 1 FROM information_schema.columns 
    WHERE table_schema='public' AND table_name='user_settings' AND column_name='settings_key'
  ) THEN 'EXISTS' ELSE 'MISSING' END as status;
